### ISSUE TITLE
Flash Xavier NX failed

### ISSUE THREAD

**Issue by ffzwadd** [jetsonhacks/bootFromExternalStorage#11]
Hardware: jetson-xavier-nx-devkit-emmc + Samsung PM961 512GB NVME
Host: Ubuntu 18.04
```
Waiting for target to boot-up...
Waiting for device to expose ssh ....................................................................................................................................................................................
...Timeout
Cleaning up...
```

**Comment by JeremieBourque1** [comment]
I have the same issue, did you end up finding a solution?

**Comment by JeremieBourque1** [comment]
I fixed my problem by using using a machine with Ubuntu 18.04 installed directly instead of using a virtual machine.

**Comment by ffzwadd** [comment]
> I fixed my problem by using using a machine with Ubuntu 18.04 installed directly instead of using a virtual machine.

I still can't get it to work, I followed the instructions but it always flash to internal EMMC instead of flash to external SSD.

**Comment by ffzwadd** [comment]
> I fixed my problem by using using a machine with Ubuntu 18.04 installed directly instead of using a virtual machine.

I still can't get it to work, I followed the instructions but it always fails. I don't have a machine with Ubuntu 18.04. I used a machine booted from a Ubuntu 18.04 Live CD.

**Comment by ffzwadd** [comment]
> I fixed my problem by using using a machine with Ubuntu 18.04 installed directly instead of using a virtual machine.

I tried on a physical machine with Ubuntu 18.04 installed directly. But still not work. Could you pleae share your story here?

**Comment by ffzwadd** [comment]
Finally, I have resolved this problem by disable USB disk automatically mount on my host system.

**Comment by ffzwadd** [comment]
Finally, I have resolved this problem by disable USB disk automatically mount on my host system.
